name: Menjalankan bot absensi otomatis

on:
  schedule:
    # Menjalankan cron job setiap pukul 6.40 pagi WIB
    # Dari hari Senin sampai Jum'at, Disini di set
    # 23:40 karena zona waktu yang dipakai github action
    # adalah zona waktu UTC, tambahkan sesuai zona waktumu
    - cron: "40 23 * * 1-5"
  workflow_dispatch:

jobs:
  absen:
    runs-on: ubuntu-latest
    name: Jalankan botnya!

    steps:
      - uses: actions/checkout@v2
      - name: Setup NodeJS 16
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.OS }}-build-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-build-${{ env.cache-name }}-
            ${{ runner.OS }}-build-
            ${{ runner.OS }}-

      - name: Install Node Dependencies
        run: npm install

      - name: Waktunya absen
        run: npm start
        env:
          # Required Field
          WEBSITE_URL: ${{ secrets.WEBSITE_URL }}
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}

          # Optional Field, uncomment if needed
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
          FORM_WRAPPER: ${{ secrets.FORM_WRAPPER }}
          # INPUT_USERNAME: ${{ secrets.INPUT_USERNAME }}
          # INPUT_PASSWORD: ${{ secrets.INPUT_PASSWORD }}
          # BUTTON_SUBMIT: ${{ secrets.BUTTON_SUBMIT }}
          SUCCESS_INDICATOR_ELEMENTS: ${{ secrets.SUCCESS_INDICATOR_ELEMENTS }}
